name: API CI

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['main']

jobs:
  setup-backend:
    name: Setup Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create empty .env file
        run: touch .env

      - name: Install dependencies
        run: make env-create

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: backend/app/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('backend/app/requirements.txt') }}
          restore-keys: venv-${{ runner.os }}-

  lint-backend:
    name: Lint Backend
    runs-on: ubuntu-latest
    needs: setup-backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore cached dependencies
        uses: actions/cache@v3
        with:
          path: backend/app/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('backend/app/requirements.txt') }}

      - name: Activate virtual environment & Run linter
        run: |
          source backend/app/.venv/bin/activate
          make lint

  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    needs: setup-backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore cached dependencies
        uses: actions/cache@v3
        with:
          path: backend/app/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('backend/app/requirements.txt') }}

      - name: Activate virtual environment & Run tests
        run: |
          source backend/app/.venv/bin/activate
          make test
