name: api-ci

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['main']

jobs:
  lint-backend:
    name: Lint Backend
    runs-on: Linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Create empty .env file
        run: touch .env

      - name: Install dependencies
        run: make env-create

      - name: Run linter
        run: |
          source backend/app/.venv/bin/activate
          make lint

  tests-backend:
    name: Tests Backend
    runs-on: Linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Create empty .env file
        run: touch .env

      - name: Install dependencies
        run: make env-create

      - name: Run tests
        run: |
          source backend/app/.venv/bin/activate
          make test
