name: front-ci

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['main']

defaults:
  run:
    working-directory: ./frontend

jobs:
  lint-frontend:
    name: Lint & Format Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load Node.js version
        run: echo "node_version=$(cat .github/nodejs.version)" >> $GITHUB_ENV

      - name: Setup Node.js & pnpm
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.node_version }}"
          cache: 'pnpm'  #Pour éviter la réinitilisation des dépendances à chaque utilisation 

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint check
        run: pnpm lint
        env:
          NEXTAUTH_SECRET: bxgh3SAToI/dvtS8/FPNcJbH2Lq+KKuS3KbKvc0x6v0=
          NEXTAUTH_URL: http://localhost:3000
          GITHUB_ID: ${{ secrets.GH_AUTH_ID }}
          GITHUB_SECRET: ${{ secrets.GH_AUTH_SECRET }}
          NEXT_PUBLIC_API_URL: http://localhost:3000/api/v1

      - name: Format check
        run: pnpm prettier --check

  test-frontend:
    name: Unit & Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load Node.js version
        run: echo "node_version=$(cat .github/nodejs.version)" >> $GITHUB_ENV

      - name: Setup Node.js & pnpm
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.node_version }}"
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test
