name: Release

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./frontend

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
